In [1]:
import torch

In [2]:
import torch.nn as nn

## Example 1
5 features -> 1 neuron -> 1 output

In [4]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    # Layer
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [5]:
# Create Dataset
features = torch.rand(10,5)

# Create an instance of model class
model = Model(features.shape[1])


# calling forward pass
model(features)

tensor([[0.3928],
        [0.4094],
        [0.4143],
        [0.3376],
        [0.3536],
        [0.3670],
        [0.4998],
        [0.5023],
        [0.3412],
        [0.3480]], grad_fn=<SigmoidBackward0>)

In [7]:
# to check weights
model.linear.weight

# to check bias
model.linear.bias

Parameter containing:
tensor([-0.2782], requires_grad=True)

In [8]:
!pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [9]:
from torchinfo import summary

In [10]:
summary(model, input_size = (10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

## Example 2
we have 5 features -> hidden layer where we implement ReLu -> 1 Output Neuron using Sigmoid -> y pred

In [11]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    # Layer
    self.linear1 = nn.Linear(num_features,3)
    self.linear2 = nn.Linear(3,1)
    self.ReLu = nn.ReLU()
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out = self.ReLu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [13]:
# Create Dataset
features = torch.rand(10,5)

# Crete a Model instance
model = Model(features.shape[1])

# train / forward Pass
model(features)

tensor([[0.5868],
        [0.5923],
        [0.5743],
        [0.5869],
        [0.5937],
        [0.5884],
        [0.5801],
        [0.5858],
        [0.5811],
        [0.5837]], grad_fn=<SigmoidBackward0>)

In [15]:
model.linear1.weight

Parameter containing:
tensor([[ 0.0557, -0.1055, -0.0191, -0.0389, -0.1545],
        [-0.0996, -0.2282,  0.2160, -0.1812,  0.3168],
        [-0.4391,  0.0207, -0.3031,  0.3203, -0.4080]], requires_grad=True)

In [16]:
model.linear1.bias

Parameter containing:
tensor([-0.2382,  0.3138, -0.3146], requires_grad=True)

In [17]:
summary(model, input_size = (10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [18]:
# this forward pass is going to be cubersome when we have multiple layers,
# solution - >Create a Sequential Container and use it in forward pass

In [21]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    # Layer
    self.network = nn.Sequential(
    nn.Linear(num_features,3),
    nn.ReLU(),
    nn.Linear(3,1),
    nn.Sigmoid()
    )


  def forward(self,features):
    out = self.network(features)
    return out

In [22]:
# Create Dataset
features = torch.rand(10,5)

# Crete a Model instance
model = Model(features.shape[1])

# train / forward Pass
model(features)

tensor([[0.5793],
        [0.5739],
        [0.5634],
        [0.5173],
        [0.5647],
        [0.5605],
        [0.5706],
        [0.5403],
        [0.5606],
        [0.4911]], grad_fn=<SigmoidBackward0>)

## Real-World Data

In [23]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [25]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [26]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [27]:
df.shape

(569, 31)

### Test - Train Split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [29]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [30]:
X_train

array([[ 0.27680272, -0.60272642,  0.29758947, ..., -0.15836183,
        -1.1782292 ,  0.15094188],
       [-0.94111351,  1.16731634, -0.94830762, ..., -1.211539  ,
         0.28150351, -0.37750443],
       [ 1.15416417,  0.60573651,  1.07711021, ..., -0.3104908 ,
        -0.86046425, -0.98896776],
       ...,
       [-0.54283759, -0.96526529, -0.56752406, ..., -0.86251036,
        -0.37719674, -0.18570647],
       [-0.10704292, -0.1430366 , -0.11993636, ...,  0.24670631,
        -0.0660519 ,  0.42690192],
       [-0.34947174, -0.72831178, -0.38506527, ..., -0.82839936,
         1.18349254, -0.70041203]])

In [31]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [33]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [54]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [65]:
X_train_tensor = X_train_tensor.to(torch.float32)

In [69]:
y_train_tensor = y_train_tensor.to(torch.float32)

In [73]:
X_test_tensor = X_test_tensor.to(torch.float32)
y_test_tensor = y_test_tensor.to(torch.float32)

### Defining Model

In [66]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [67]:
learning_rate = 0.1
epochs = 25
loss_function = nn.BCELoss()

In [70]:
# Create an instance of Model Class
model = Model(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
# defining loop
for epoch in range(epochs):
  # Forward pass
  ypred = model(X_train_tensor)

  # Calculate Loss
  loss = loss_function(ypred, y_train_tensor.view(-1,1))

  optimizer.zero_grad()
  # bakward pass
  loss.backward()

  # optimize / Update parameters
  optimizer.step()

In [74]:
with torch.no_grad():
  ypred = model.forward(X_test_tensor)
  ypred = (ypred > 0.9).float()
  accuracy = (ypred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5360110998153687