In [18]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [11]:
df = pd.read_csv('Data/spam.csv',encoding='ISO-8859-1')
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [12]:
# 1. Data Cleaning
# 2. EDA
# 3. Model Fitting
# 4. Evaluation

## 1. Data Cleaning

In [13]:
# check for missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [15]:
# dropping last 3 columns
df.drop(columns = ['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace = True)
df.sample(5)

       v1                                                 v2
406   ham  All was well until slightly disastrous class t...
2214  ham  Ok then i'll let him noe later n ask him call ...
5018  ham                    Great! How is the office today?
349   ham  Just checking in on you. Really do miss seeing...
4868  ham  1. Tension face 2. Smiling face 3. Waste face ...

In [17]:
# rename v1 and v2
df.rename(columns = {'v1': 'target', 'v2':'text'},inplace = True)
df.sample(5)

     target                                               text
941     ham  Theyre doing it to lots of places. Only hospit...
4928   spam  Got what it takes 2 take part in the WRC Rally...
49      ham  U don't know how stubborn I am. I didn't even ...
2818    ham  Don't forget who owns you and who's private pr...
4905    ham                   Will you come online today night

In [21]:
# let's label encode our target variable 1: Spam | 0: Not Spam
encoder = LabelEncoder()
df['target'] = encoder.fit_transform(df['target'])

In [23]:
df.sample(5)

      target                                               text
3362       0                                 Can... I'm free...
1309       0            Ok, be careful ! Don't text and drive !
2820       0              Oh god..taken the teeth?is it paining
4666       0                         I send the print  outs da.
2847       0  Sad story of a Man - Last week was my b'day. M...

In [25]:
# Let's check for null and duplicate values
df.isnull().sum()

target    0
text      0
dtype: int64

In [27]:
df.duplicated().sum()

np.int64(403)

In [28]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [29]:
df.shape

(5169, 2)

## 2. EDA

In [31]:
# Checking value sparsity
df['target'].value_counts() # Somewhat imbalance dataset

target
0    4516
1     653
Name: count, dtype: int64